### ISSUE TITLE
Discussão de pagamento

### ISSUE THREAD

**Issue by LeonardoFreitas1** [apontes77/projetoApp_CMP1118#3]
## Metodologia de pagamento

A ideia inicial seria de uma forma de destaque de anuncio, onde o usuario que esta anunciando o
serviço pagaria uma quantia para o aplicativo, e seu anuncio ficaria destacado para todos os
contratantes do aplicativo.

A segunda ideia seria tornar o app pago para os usuarios que estao anunciando, sendo que inicialmente o app benificiaria o usuario a um ano gratis de uso no app.

**Comment by apontes77** [comment]
O novo usuário recebe, ao criar conta na aplicação, 5 contratações com 50% de desconto, de modo que tal condição também é compartilhada com o usuário trabalhador, que vende sua força de trabalho.

Após isso, o aplicativo oferece novas categorias de perfil contratante para o usuário.

**Comment by LeonardoFreitas1** [comment]
discordo, pois assim o prestador de serviço acaberia sendo prejudicado por isso.

**Comment by apontes77** [comment]
> discordo, pois assim o prestador de serviço acaberia sendo prejudicado por isso.

Falar é fácil. Argumente a respeito. Como ocorre o tal "prejuízo" para o prestador de serviço?
